apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkin-springboot-app-depl1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkin-springboot-app1
  template:
    metadata:
      labels:
        app: jenkin-springboot-app1
    spec:
      containers:
        - name: jenkin-springboot-app1
          image: rohitaggarwal88/jenkinspringbootnew1q
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---	  
  apiVersion: v1 # Kubernetes API version
  kind: Service # Kubernetes resource kind we are creating
  metadata: # Metadata of the resource kind we are creating
    name: jenkin-springboot-svc1
  spec:
    selector:
      app: jenkin-springboot-app1
    ports:
      - protocol: "TCP"
        port: 80 # The port that the service is running on in the cluster
        targetPort: 8080 # The port exposed by the service
    type: NodePort # type of the service.